[project]
name = "fraud-detection-inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "numpy>=2.2.3",
    "onnxruntime>=1.20.1",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
